## **Logistic Regression**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy as stats
import math

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y = make_classification(n_features=4,n_classes=2)

In [4]:
print(X)

[[ 0.36501459 -0.12534977  1.95795894 -0.94559793]
 [ 2.23175682 -0.24075106 -1.96354504 -1.56769139]
 [ 2.29051521 -0.24448012 -2.08441798 -1.58804741]
 [ 1.12307169 -0.1174164  -1.08711628 -0.75895678]
 [ 1.61018738 -0.2339095   0.17945913 -1.61373771]
 [-0.67440507  0.14021449 -1.1950417   1.01453952]
 [ 1.54325518 -0.16354552 -1.43554793 -1.06054075]
 [-1.09458192  0.24129039 -2.30323666  1.75659629]
 [-1.77044385  0.32153907 -1.90317773  2.29019344]
 [ 0.6966694  -0.0717363  -0.70352626 -0.46198167]
 [ 0.63711549 -0.14413932  1.43853125 -1.05205495]
 [-0.73683334  0.07529447  0.75939534  0.4839859 ]
 [-1.59380488  0.21354044  0.299248    1.45311172]
 [-0.56216681  0.05831231  0.55641241  0.37620239]
 [ 1.40900605 -0.21518492  0.43540431 -1.49629017]
 [-1.47040366  0.27801363 -1.87135318  1.98998024]
 [ 1.42538362 -0.21552769  0.38324673 -1.4963796 ]
 [ 0.57152486 -0.14215841  1.63129587 -1.04682169]
 [ 1.33252219 -0.20779048  0.52539534 -1.44942839]
 [ 0.66100727 -0.06810301 -0.66

In [5]:
print(X.shape)

(100, 4)


In [6]:
X_df= pd.DataFrame(X,columns=['feature_1','feature_2','feature_3','feature_4'])

In [7]:
y_df = pd.DataFrame(y,columns=['target'])

In [8]:
df = pd.concat([X_df,y_df],axis=1)

In [9]:
print(df)

    feature_1  feature_2  feature_3  feature_4  target
0    0.365015  -0.125350   1.957959  -0.945598       1
1    2.231757  -0.240751  -1.963545  -1.567691       0
2    2.290515  -0.244480  -2.084418  -1.588047       0
3    1.123072  -0.117416  -1.087116  -0.758957       0
4    1.610187  -0.233909   0.179459  -1.613738       1
..        ...        ...        ...        ...     ...
95   0.882942  -0.088960  -0.943519  -0.569815       0
96   1.818309  -0.250411  -0.161381  -1.712235       1
97  -2.104275   0.298416  -0.041832   2.050645       1
98   1.294233  -0.135154  -1.256971  -0.873363       0
99  -1.556610   0.293893  -1.969935   2.103282       0

[100 rows x 5 columns]


**split dataset**

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X_df,y_df,test_size=0.1,random_state=41) 

**standardize data**

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

In [14]:
data = scaler.fit_transform(df)

In [15]:
df

feature_1  feature_2  feature_3  feature_4  target
0    0.365015  -0.125350   1.957959  -0.945598       1
1    2.231757  -0.240751  -1.963545  -1.567691       0
2    2.290515  -0.244480  -2.084418  -1.588047       0
3    1.123072  -0.117416  -1.087116  -0.758957       0
4    1.610187  -0.233909   0.179459  -1.613738       1
..        ...        ...        ...        ...     ...
95   0.882942  -0.088960  -0.943519  -0.569815       0
96   1.818309  -0.250411  -0.161381  -1.712235       1
97  -2.104275   0.298416  -0.041832   2.050645       1
98   1.294233  -0.135154  -1.256971  -0.873363       0
99  -1.556610   0.293893  -1.969935   2.103282       0

[100 rows x 5 columns]

In [16]:
data

array([[ 0.24199399, -0.67634409,  1.64151471, -0.74057161,  1.        ],
       [ 1.77894654, -1.32220845, -1.41732056, -1.24076967, -1.        ],
       [ 1.82732432, -1.34307885, -1.51160337, -1.25713706, -1.        ],
       [ 0.86612826, -0.63194357, -0.73369223, -0.59050166, -1.        ],
       [ 1.26718722, -1.28391842,  0.25425666, -1.2777935 ,  1.        ],
       [-0.61379566,  0.80993471, -0.81787578,  0.8354889 , -1.        ],
       [ 1.21207966, -0.89011359, -1.00547445, -0.83299209, -1.        ],
       [-0.9597416 ,  1.37562441, -1.68228541,  1.4321442 , -1.        ],
       [-1.51620178,  1.82475081, -1.37023311,  1.86118626, -1.        ],
       [ 0.51505671, -0.37628654, -0.43448594, -0.351717  , -1.        ],
       [ 0.46602394, -0.78150323,  1.23635288, -0.82616903,  1.        ],
       [-0.66519499,  0.446598  ,  0.7066161 ,  0.40889402,  1.        ],
       [-1.37076889,  1.2203168 ,  0.34769388,  1.18812557,  1.        ],
       [-0.52138608,  0.35155424,  0.5

**functions for logistic regression**

In [17]:
def initalize(self,X):
  weights = np.zero((X.shape[1]+1,1))
  X = np.c_[np.ones((X.shape[0],1)),X]
  return weights,X

In [18]:
def sigmoid(self,z):
  sig = 1/1+math.e**(-z)
  return sig

In [19]:
def cost(self,theta):
  z = np.dot(X,theta)
  cost0 = y.T.dot(math.log(self.sigmoid(z)))
  cost1 = (1-y).T.dot(math.log(1-self.sigmoid(z)))

  cost = -((cost1+cost0))/len(y)
  return cost

In [20]:
def fit(self,X,y,alpha = 0.001,itr = 100):
  para , X = self.initalize(X)
  cost_list = np.zero(itr)
  for i in range(itr):
    para  = para-alpha*np.dot(X.T,self.sigmoid(np.dot(X,para) - np.reshape(y,(len (y),1))))
    cost_list[i] = cost(para)
    self.para = para
    return cost_list

In [21]:
def predict(self,X):
  Z = np.dot(self.initialize(X)[1],self.weights)
  lis = []
  for i in self.sigmoid(Z):
    if (i>0.5):
      lis.append(1)
    else:
      lis.append(0)
    return lis 

In [22]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state = 0)
clf.fit(X_train, y_train)


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [23]:
clf = clf.fit(X_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [24]:
clf = clf.fit(X_test,y_test)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [25]:
y_train_pred = clf.predict(X_train)
y_test_pred = clf.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [27]:
print("Accuracy:",accuracy_score(y_test,y_test_pred))

Accuracy: 0.9
